version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  backend:
    build: ./backend
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/countries-app
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=30d
    ports:
      - "5000:5000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://${EC2_HOST:-localhost}:5000
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VITE_API_URL=http://${EC2_HOST:-localhost}:5000
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 