version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  
  backend:
    build: ./backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/countries-app
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=30d
      - NODE_ENV=production
    ports:
      - "5000:5000"
    networks:
      - app-network
  
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://${EC2_HOST:-localhost}:5000
    restart: always
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://${EC2_HOST:-localhost}:5000
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 